version: "3.7"

networks:
    monzo:
        driver: bridge
services:
    plugin.budget:
        image: reecerussell/monzo-plus-plus:plugin.budget
        build:
            context: .
            dockerfile: service.plugin.budget/Dockerfile
        ports:
            - "9876:8080"
        environment:
            - "CONN_STRING=root:password@tcp(host.docker.internal)/monzo_plus_plus?parseTime=true"
            - "HTTP_PORT=80"
            - "RPC_PORT=8080"
        networks:
            - monzo

    mpp:
        image: reecerussell/monzo-plus-plus
        build:
            context: .
            dockerfile: service.mpp/Dockerfile.dev
        restart: unless-stopped
        ports:
            - "9789:80"
        environment:
            - "MONZO_CLIENT_ID=<monzo client id>"
            - "MONZO_CLIENT_SECRET=<monzo client secret>"
            - "OAUTH_CALLBACK_URL=http://localhost:9789/monzo/callback"
            - "SUCCESS_CALLBACK_URL=http://localhost:9789/monzo/callback"
            - "CONN_STRING=root:password@tcp(host.docker.internal)/monzo_plus_plus?parseTime=true"
            - "HTTP_PORT=80"
            - "BUDGET_RPC_HOST=plugin.budget:8080"
        networks:
            - monzo
        depends_on:
            - plugin.budget
