version: "3.7"

networks:
    monzo:
        driver: bridge

services:
    db:
        image: reecerussell/mpp-db
        build: ./service.mysql
        restart: always
        networks:
            - monzo

    plugin.budget:
        image: reecerussell/mpp-plugin-budget
        build:
            context: .
            dockerfile: service.plugin.budget/Dockerfile
        environment:
            - "CONN_STRING=monzo:m0nz0-Pl5s-pluS@tcp(db)/monzo_plus_plus?parseTime=true"
            - "HTTP_PORT=80"
            - "RPC_PORT=8080"
            - "NAME=budget"
            - "HOSTNAME=plugin.budget"
            - "REGISTRY_HOST=registry:8080"
            - "AUTH_RPC_ADDRESS=auth:8080"
        networks:
            - monzo
        depends_on:
            - db
            - registry

    registry:
        image: reecerussell/mpp-registry
        build:
            context: .
            dockerfile: service.registry/Dockerfile
        environment:
            - "RPC_PORT=8080"
        networks:
            - monzo

    job_queue:
        image: reecerussell/mpp-job-queue
        build:
            context: .
            dockerfile: service.job_queue/Dockerfile
        environment:
            - "HTTP_PORT=80"
            - "RPC_PORT=8080"
            - "CONN_STRING=monzo:m0nz0-Pl5s-pluS@tcp(db)/monzo_plus_plus?parseTime=true"
            - "REGISTRY_HOST=registry:8080"
            - "AUTH_RPC_HOST=auth:8080"
            - "WORKER_LIMIT=3"
        networks:
            - monzo
        depends_on:
            - db
            - registry

    auth:
        image: reecerussell/mpp-auth
        build:
            context: .
            dockerfile: service.auth/Dockerfile
        environment:
            - "MONZO_WEBHOOK_URL=https://mpp.reece-russell.co.uk/api/monzo/hook"
            - "MONZO_CLIENT_ID=oauth2client_00009s8M2iOG06xOrzfwVm"
            - "MONZO_CLIENT_SECRET=mnzconf.Lq8WbdehEdPfQTjEc0BQvxC3DciZK++gk/ib0IXUEUr81okDA4AhHM4+jAPNGvLa5rgIug3lpsXBd8Nx4B95"
            - "OAUTH_CALLBACK_URL=https://mpp.reece-russell.co.uk/api/auth/monzo/callback"
            - "SUCCESS_CALLBACK_URL=https://mpp.reece-russell.co.uk/#login"
            - "CONN_STRING=monzo:m0nz0-Pl5s-pluS@tcp(db)/monzo_plus_plus?parseTime=true"
            - "HTTP_PORT=80"
            - "RPC_PORT=8080"
        restart: unless-stopped
        networks:
            - monzo
        depends_on:
            - db

    plugins:
        image: reecerussell/mpp-plugins
        build:
            context: .
            dockerfile: service.plugins/Dockerfile
        environment:
            - "CONN_STRING=monzo:m0nz0-Pl5s-pluS@tcp(db)/monzo_plus_plus?parseTime=true"
            - "HTTP_PORT=80"
            - "HTTP_ERROR=DEBUG"
            - "AUTH_RPC_ADDRESS=auth:8080"
        networks:
            - monzo
        depends_on:
            - db

    mpp:
        image: reecerussell/mpp-entrypoint
        build:
            context: .
            dockerfile: service.mpp/Dockerfile
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:80"
        environment:
            - "CONN_STRING=monzo:m0nz0-Pl5s-pluS@tcp(db)/monzo_plus_plus?parseTime=true"
            - "HTTPS_PORT=443"
            - "AUTH_HTTP_HOST=http://auth:80"
            - "PLUGINS_HTTP_HOST=http://plugins:80"
            - "JOBS_HOST=job_queue:8080"
            - "REGISTRY_HOST=registry:8080"
        networks:
            - monzo
        depends_on:
            - registry
            - db
