version: "3.7"

networks:
    monzo:
        driver: bridge
services:
    plugin.budget:
        image: reecerussell/monzo-plus-plus:plugin.budget
        build:
            context: .
            dockerfile: service.plugin.budget/Dockerfile
        environment:
            - "CONN_STRING=root:password@tcp(host.docker.internal)/monzo_plus_plus?parseTime=true"
            - "HTTP_PORT=80"
            - "RPC_PORT=8080"
        networks:
            - monzo
        depends_on:
            - registry

    registry:
        build:
            context: .
            dockerfile: service.registry/Dockerfile
        environment:
            - "RPC_PORT:8080"
        networks:
            - monzo

    auth:
        image: reecerussell/monzo-plus-plus:auth
        build:
            context: .
            dockerfile: service.auth/Dockerfile
        environment:
            - "CONN_STRING=root:password@tcp(host.docker.internal)/monzo_plus_plus?parseTime=true"
            - "HTTP_PORT=80"
            - "RPC_PORT=8080"
            - "HTTP_ERROR=DEBUG"
        networks:
            - monzo

    mpp:
        image: reecerussell/monzo-plus-plus
        build:
            context: .
            dockerfile: service.mpp/Dockerfile.dev
        restart: unless-stopped
        ports:
            - "9789:80"
        environment:
            - "MONZO_CLIENT_ID=oauth2client_00009s8M2iOG06xOrzfwVm"
            - "MONZO_CLIENT_SECRET=mnzconf.Lq8WbdehEdPfQTjEc0BQvxC3DciZK++gk/ib0IXUEUr81okDA4AhHM4+jAPNGvLa5rgIug3lpsXBd8Nx4B95"
            - "OAUTH_CALLBACK_URL=http://localhost:9789/monzo/callback"
            - "SUCCESS_CALLBACK_URL=http://localhost:9789/monzo/callback"
            - "CONN_STRING=root:password@tcp(host.docker.internal)/monzo_plus_plus?parseTime=true"
            - "HTTP_PORT=80"
            - "BUDGET_HTTP_HOST=http://plugin.budget:80"
            - "AUTH_HTTP_HOST=http://auth:80"
            - "MONZO_WEBHOOK_URL="
        networks:
            - monzo
        depends_on:
            - registry
