// Code generated by protoc-gen-go. DO NOT EDIT.
// source: budget_service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CalculateData struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	AccountID            string   `protobuf:"bytes,2,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
	AccessToken          string   `protobuf:"bytes,3,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculateData) Reset()         { *m = CalculateData{} }
func (m *CalculateData) String() string { return proto.CompactTextString(m) }
func (*CalculateData) ProtoMessage()    {}
func (*CalculateData) Descriptor() ([]byte, []int) {
	return fileDescriptor_e75542dc2234d8f7, []int{0}
}

func (m *CalculateData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateData.Unmarshal(m, b)
}
func (m *CalculateData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateData.Marshal(b, m, deterministic)
}
func (m *CalculateData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateData.Merge(m, src)
}
func (m *CalculateData) XXX_Size() int {
	return xxx_messageInfo_CalculateData.Size(m)
}
func (m *CalculateData) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateData.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateData proto.InternalMessageInfo

func (m *CalculateData) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *CalculateData) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *CalculateData) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type CalculateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculateResponse) Reset()         { *m = CalculateResponse{} }
func (m *CalculateResponse) String() string { return proto.CompactTextString(m) }
func (*CalculateResponse) ProtoMessage()    {}
func (*CalculateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e75542dc2234d8f7, []int{1}
}

func (m *CalculateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateResponse.Unmarshal(m, b)
}
func (m *CalculateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateResponse.Marshal(b, m, deterministic)
}
func (m *CalculateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateResponse.Merge(m, src)
}
func (m *CalculateResponse) XXX_Size() int {
	return xxx_messageInfo_CalculateResponse.Size(m)
}
func (m *CalculateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CalculateData)(nil), "proto.CalculateData")
	proto.RegisterType((*CalculateResponse)(nil), "proto.CalculateResponse")
}

func init() { proto.RegisterFile("budget_service.proto", fileDescriptor_e75542dc2234d8f7) }

var fileDescriptor_e75542dc2234d8f7 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x2a, 0x4d, 0x49,
	0x4f, 0x2d, 0x89, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x05, 0x53, 0x4a, 0xe9, 0x5c, 0xbc, 0xce, 0x89, 0x39, 0xc9, 0xa5, 0x39, 0x89, 0x25,
	0xa9, 0x2e, 0x89, 0x25, 0x89, 0x42, 0x62, 0x5c, 0x6c, 0xa1, 0xc5, 0xa9, 0x45, 0x9e, 0x2e, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x50, 0x9e, 0x90, 0x0c, 0x17, 0xa7, 0x63, 0x72, 0x72, 0x7e,
	0x69, 0x5e, 0x89, 0xa7, 0x8b, 0x04, 0x13, 0x58, 0x0a, 0x21, 0x20, 0xa4, 0xc0, 0xc5, 0xed, 0x98,
	0x9c, 0x9c, 0x5a, 0x5c, 0x1c, 0x92, 0x9f, 0x9d, 0x9a, 0x27, 0xc1, 0x0c, 0x96, 0x47, 0x16, 0x52,
	0x12, 0xe6, 0x12, 0x84, 0x5b, 0x14, 0x94, 0x5a, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x6a, 0xe4, 0xc7,
	0xc5, 0xeb, 0x04, 0x76, 0x5c, 0x30, 0xc4, 0x6d, 0x42, 0xb6, 0x5c, 0x9c, 0x70, 0x55, 0x42, 0x22,
	0x10, 0xa7, 0xea, 0xa1, 0x38, 0x50, 0x4a, 0x02, 0x5d, 0x14, 0x66, 0x9a, 0x12, 0x43, 0x12, 0x1b,
	0x58, 0xca, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x34, 0x0c, 0xd2, 0xf3, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BudgetServiceClient is the client API for BudgetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BudgetServiceClient interface {
	Calculate(ctx context.Context, in *CalculateData, opts ...grpc.CallOption) (*CalculateResponse, error)
}

type budgetServiceClient struct {
	cc *grpc.ClientConn
}

func NewBudgetServiceClient(cc *grpc.ClientConn) BudgetServiceClient {
	return &budgetServiceClient{cc}
}

func (c *budgetServiceClient) Calculate(ctx context.Context, in *CalculateData, opts ...grpc.CallOption) (*CalculateResponse, error) {
	out := new(CalculateResponse)
	err := c.cc.Invoke(ctx, "/proto.BudgetService/Calculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BudgetServiceServer is the server API for BudgetService service.
type BudgetServiceServer interface {
	Calculate(context.Context, *CalculateData) (*CalculateResponse, error)
}

// UnimplementedBudgetServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBudgetServiceServer struct {
}

func (*UnimplementedBudgetServiceServer) Calculate(ctx context.Context, req *CalculateData) (*CalculateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculate not implemented")
}

func RegisterBudgetServiceServer(s *grpc.Server, srv BudgetServiceServer) {
	s.RegisterService(&_BudgetService_serviceDesc, srv)
}

func _BudgetService_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BudgetServiceServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BudgetService/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BudgetServiceServer).Calculate(ctx, req.(*CalculateData))
	}
	return interceptor(ctx, in, info, handler)
}

var _BudgetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BudgetService",
	HandlerType: (*BudgetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _BudgetService_Calculate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "budget_service.proto",
}
